name       : xrdb
version    : 1.2.0
release    : 8
source     :
    - https://www.x.org/releases/individual/app/xrdb-1.2.0.tar.gz : 7dec50e243d55c6a0623ff828355259b6a110de74a0c65c40529514324ef7938
license    : MIT
component  : xorg.apps
summary    : |
    X.Org Applications: xrdb
description: |
    X.Org Applications: xrdb
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
