name       : xrdb
version    : 1.1.0
release    : 3
source     :
    - https://www.x.org/releases/individual/app/xrdb-1.1.0.tar.gz : 44b0b6b7b7eb80b83486dfea67c880f6b0059052386c7ddec4d58fd2ad9ae8e9
license    :
    - MIT
summary    : |
    X.Org Applications: xrdb
component  : xorg.apps
description: |
    X.Org Applications: xrdb
builddeps  :
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
    - pkgconfig(x11)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
