name       : xrdb
version    : 1.1.1
release    : 4
source     :
    - https://www.x.org/releases/individual/app/xrdb-1.1.1.tar.gz : d19f856296c5f1742a703afc620654efc76fedfb86e1afe0bff9f1038b9e8a47
license    :
    - MIT
summary    : |
    X.Org Applications: xrdb
component  : xorg.apps
description: |
    X.Org Applications: xrdb
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
